#!/bin/sh

case "$1" in
  start)
        echo "Deleting dhcpcd..."
        if [ -f /etc/init.d/S41dhcpcd ]; then
                rm /etc/init.d/S41dhcpcd
        fi
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
